.gitignore
Gitignore added for easier commiting. Copied from Orange3 and modified.
=> Added gitignore file.

orangecontrib/network/snap.py, orangecontrib/network/widgets/OWNxAnalysis.py, orangecontrib/network/widgets/OWNxFile.py, orangecontrib/network/widgets/OWNxSNAP.py, orangecontrib/network/widgets/graphview.py
Replace uses of obsolete Qt4/PyQt4 features
=> PyQt modernize

setup.py
=> Error message for setup.py

orangecontrib/network/widgets/OWNxExplorer.py, orangecontrib/network/widgets/graphview.py
A proposed fix for https://github.com/biolab/orange3-network/issues/12.
=> Output unselected subgraph in Explorer

orangecontrib/network/community.py, orangecontrib/network/widgets/OWNxClustering.py
- hidden main area removed
- added Items as output
- remapped labels to be consistent with Orange
=> OWNxClustering: modernized

orangecontrib/network/widgets/OWNxAnalysis.py, orangecontrib/network/widgets/OWNxClustering.py
Fixed auto commit on ticking *Commit automatically* and set the box to standard Orange commit box.
=> Autocommit and modernization of widget.

orangecontrib/network/widgets/OWNxAnalysis.py, orangecontrib/network/widgets/OWNxClustering.py, orangecontrib/network/widgets/OWNxExplorer.py, orangecontrib/network/widgets/OWNxFile.py, orangecontrib/network/widgets/OWNxFromDistances.py, orangecontrib/network/widgets/OWNxGenerator.py, orangecontrib/network/widgets/graphview.py, requirements.txt, setup.py
Widgets: Change imports to AnyQt
=> Widgets: Change imports to AnyQt

orangecontrib/network/widgets/OWNxExplorer.py, orangecontrib/network/widgets/OWNxFile.py, orangecontrib/network/widgets/OWNxFromDistances.py
Removed old (obsolete) and added new warning and error calls.
=> Widgets: Update  warning and error messages.

orangecontrib/network/widgets/OWNxFile.py
Removed annoying main area and aligned the buttons correctly. OCD.
=> Main area removed and buttons aligned.

orangecontrib/network/widgets/OWNxExplorer.py
Fixes https://github.com/biolab/orange3-network/issues/40.
@ajdapretnar Please see if this is performant enough for you.
=> OWNxExplorer: Fix stalling on very wide datasets

orangecontrib/network/widgets/OWNxAnalysis.py, orangecontrib/network/widgets/OWNxClustering.py, orangecontrib/network/widgets/OWNxExplorer.py, orangecontrib/network/widgets/OWNxFile.py, orangecontrib/network/widgets/OWNxFromDistances.py, orangecontrib/network/widgets/OWNxGenerator.py
=> [FIX] New signals

orangecontrib/network/widgets/OWNxExplorer.py
=> [FIX] Network Explorer: fix new signals set graph

orangecontrib/network/widgets/OWNxClustering.py, orangecontrib/network/widgets/OWNxExplorer.py
=> [FIX] Network Explorer: new signals

orangecontrib/network/widgets/OWNxExplorer.py, orangecontrib/network/widgets/graphview.py
See #16 :
> 1.) Network Explorer should display legend if coloring by attribute.
=> [ENH] Network Explorer: add legend

orangecontrib/network/widgets/OWNxAnalysis.py
No settings.
Implemented settings.
=> [FIX] Network Analysis: settings

orangecontrib/network/widgets/OWNxExplorer.py
Settings does not work. Some dead code and some things not imported.
=> [FIX] Network Explorer: settings

orangecontrib/network/widgets/OWNxExplorer.py
Now the size of nodes can be easily changed.
=> [ENH] Network Explorer: size slider

orangecontrib/network/widgets/OWNxExplorer.py
Width of edges cannot not be changed.
Add size (width) slider.
=> [FIX] Network Explorer: set edge size (width)

orangecontrib/network/readwrite.py, orangecontrib/network/widgets/OWNxFile.py
Reading `pajek` format may fail.
Do not crash a program due to that reading (parse) error.
=> [FIX] Network File: handle pajek bug & two small fixes

orangecontrib/network/community.py, orangecontrib/network/network.py, orangecontrib/network/readwrite.py, orangecontrib/network/setup.py, orangecontrib/network/widgets/OWNxAnalysis.py, orangecontrib/network/widgets/OWNxClustering.py, orangecontrib/network/widgets/OWNxExplorer.py, orangecontrib/network/widgets/OWNxFile.py, orangecontrib/network/widgets/OWNxFromDistances.py, orangecontrib/network/widgets/OWNxGenerator.py, orangecontrib/network/widgets/graphview.py
No real issue.
Changing style.
=> [FIX] Networks: cleaning

.travis.yml
Pull request are not tested against the latest version of Orange.
Pip install Orange before running tests.
=> .travis: Add pip install Orange

setup.py
It would seem that I'm an idiot unable to prepare a proper release of an add-on, but I'll keep pushing.
=> Version bump (1.4.1)

orangecontrib/network/widgets/OWNxExplorer.py
Needs merge of https://github.com/biolab/orange3/pull/3432
=> Projections: Move OWPlotGUI instance from graph to widget

orangecontrib/network/widgets/OWNxGroups.py, orangecontrib/network/widgets/tests/test_OWNxGroups.py
Widget currently supports only weighting by sum of weights of connections.
This PR adds various weighting options.
=> NXGroups: Add different weights and normalizations

orangecontrib/network/readwrite.py
Fixes #88.
Create a table for empty graph.
=> readwrite.graph_to_table: Return an empty table for empty graph

orangecontrib/network/widgets/OWNxFromDistances.py
Network from distances attached wrong item info for distances from columns.
Use attribute names instead of table.
=> [FIX] NxFromDistances: Proper labels for column distances

orangecontrib/network/widgets/OWNxFromDistances.py
=> NxFromDistances: Change the background color to white

orangecontrib/network/widgets/OWNxFromDistances.py
=> OWNxFromDistances: Fix crash when no edges and inverse is checked

orangecontrib/network/widgets/OWNxFromDistances.py
=> OWNxFromDistances: Fix crash when the matrix is empty

orangecontrib/network/widgets/tests/test_OWNxClustering.py, orangecontrib/network/widgets/tests/test_OWNxExplorer.py, orangecontrib/network/widgets/tests/test_OWNxFile.py, orangecontrib/network/widgets/tests/test_OWNxGenerator.py, orangecontrib/network/widgets/tests/test_OWNxGroups.py, orangecontrib/network/widgets/tests/test_ownxsinglemode.py, orangecontrib/network/widgets/tests/utils.py
Network tests would benefit from utility functions for loading the data.
Extend `WidgetTest` class with utility functions. Now, `NetworkTest` should be used.
=> Utils for network testing

orangecontrib/network/network/community.py, orangecontrib/network/widgets/OWNxClustering.py, orangecontrib/network/widgets/tests/test_OWNxClustering.py
Fixes #124.  
1. Adds replicable clustering option (i.e. set seed 0)  
2. Results from multiple reruns of clustering are saved to one feature instead of creating a new feature for every rerun. A unique feature name is tied to an instance of `Network Clustering` widget and keeps getting overriden on reruns. If network is detached from input, this feature name is cleared and a new one is reassigned when a new network is attached to the widget.
=> Network Clustering fixes

orangecontrib/network/network/readwrite.py, orangecontrib/network/tests/test_readwrite.py, orangecontrib/network/widgets/OWNxFile.py, orangecontrib/network/widgets/OWNxSave.py, orangecontrib/network/widgets/icons/NetworkSave.svg
Fixes #80.
Requires https://github.com/biolab/orange3/pull/3994.
=> [ENH] Widget for saving networks

doc/conf.py, doc/index.rst
Doc setup was not correct.
Fix conf.py and index.rst to work with .md files.
=> Build documentation properly

doc/widgets.json, doc/widgets/networkofgroups.md, orangecontrib/network/widgets/OWNxFromDistances.py
Widget json was wrong.
Fix files to be able to auto-generate widgets.json file.
I decided to put camel case to all.
=> Fix widgets.json

doc/widgets/networkanalysis.md, doc/widgets/networkclustering.md, doc/widgets/networkfile.md, doc/widgets/networkfromdistances.md, doc/widgets/networkgenerator.md
On case-sensitive file systems, documentation doesn't get built properly.
Match image paths exactly.
Lint one doc.
=> Image path and lint

README.pypi, setup.py
README for Github and README for PyPi should not be the same. PyPi doesn't format markdown and the description is often too long.
Have two separate READMEs - one for Github and one for PyPi (which is also shown in the add-on dialogue).
=> Provide separate README for PyPi

orangecontrib/network/widgets/ownxsinglemode.py
ownxsinglemode stoped worked due to changes in domain
Fixed sum of tuple and list
=> Fix changed domain values type

orangecontrib/network/network/base.py
=> Fix typo in call of _compute_degrees

doc/widgets/singlemode.md
Closes #129.
Following the discussion in #129, the widget stays as it is, but we improve the documentation.
Clarified the introductory paragraph, replaced "with" with "by" in the example seciton.
=> Single Mode: Improve documentation

orangecontrib/network/widgets/OWNxFile.py, orangecontrib/network/widgets/tests/networks/test_data.tab, orangecontrib/network/widgets/tests/test_OWNxFile.py
=> Network File: Allow user to choose a column to match node labels

orangecontrib/network/widgets/graphview.py, orangecontrib/network/widgets/tests/test_graphview.py
Fixes #174: draw loops.
Besides, edges, in particular with arrows, are ugly. This PR makes them shorter, nicer.
No tests, it's all in `paint`.
=> [ENH] Draw nicer arrows, shorten the edges

.github/workflows/build_wheels.yml, pyproject.toml
=> CI: GH Actions build wheels

.github/workflows/build_wheels.yml
=> CI: fix source dist build

.github/workflows/build_wheels.yml
=> CI: pypi publish

orangecontrib/network/widgets/OWNxGenerator.py
Radio buttons are put into boxes that also contain labels and spins, which broke spacing.
- Fix spacing
- Simplify
- Properly define minimal and maximal value for spins
- Remove unnecessary box name
=> Generate Network: Refactor UX after changes in orange-widget-base

orangecontrib/network/widgets/OWNxGroups.py
Same problem as in https://github.com/biolab/orange3/pull/5324.
=> Groups: Fix crash on empty table

orangecontrib/network/widgets/OWNxFromDistances.py
In part because of recent changes in orange-widget-base, but also before that, this widget's layout was not nice.
I changed it to use `QGridLayout`.
=> Network from Distances: Improve UX

orangecontrib/network/widgets/OWNxExplorer.py
=> Network Explorer: Add box titles

orangecontrib/network/widgets/OWNxExplorer.py
Relevant after https://github.com/biolab/orange3/pull/5319 is merged.
[Edit, JD]: ... and Orange 3.29 is released.
Remove duplicated code (code was moved to base class).
=> OWDataProjectionWidget: Move common code to base class

orangecontrib/network/widgets/OWNxFile.py, orangecontrib/network/widgets/ownxsinglemode.py
Fixes ugly widget GUI.
Remove double controls at the bottom of Network Explorer.
Set Network File to fixed size to avoid over large window on open???
=> Fix GUI issues

orangecontrib/network/widgets/OWNxExplorer.py, orangecontrib/network/widgets/tests/test_OWNxExplorer.py
Fixes #218.
Use the attribute that is present in the new implementation of `Network`.
=> Network Explorer: Fix crashing report

orangecontrib/network/widgets/OWNxClustering.py, orangecontrib/network/widgets/OWNxFile.py, orangecontrib/network/widgets/OWNxSave.py, orangecontrib/network/widgets/__init__.py
Fixes #217.
Register `summarize` for networks.
=> Add summaries to widgets

orangecontrib/network/widgets/OWNxAnalysis.py
Fixes #223. I think.
This is surprisingly complicated. Data is output when jobs are finished. If there are no jobs, nothing is finished, so no output. Furthermore, data is output only if some node-level index changed. And we don't won't output when some, but not all jobs are done. And, oh, yes, when the user enables, disables and re-enables a checkbox, no jobs are run at re-enabling because the previously computed index is still cached. You get the picture. :)
I think this fix ought to do it -- I made the code as clear as I can, and I clicked some. Please do some more clicking. :)
I won't write tests, I don't know how to.
=> Network Analysis: Output data also when no node level stats

orangecontrib/network/widgets/OWNxFile.py
=> [FIX] Network File: Do not re-send data when browsing is cancelled

orangecontrib/network/widgets/OWNxFromDistances.py, orangecontrib/network/widgets/OWNxNeighbor.py, orangecontrib/network/widgets/tests/test_OWNxFromDistances.py, orangecontrib/network/widgets/tests/test_utils.py, orangecontrib/network/widgets/utils.py
Add weights to Network From Distances and From Neighbors
=> Add weights to Network From Distances and From Neighbors
