doc/index.rst
Documentation doesn't open when F1 is pressed.
Use title instead of caption so `Orange.canvas.help.provider.HtmlIndexProvider` will correctly parse documentation webpage.
=> Doc: Fix opening documentation on F1

.travis.yml
No Travis and therefore no testing.
=> [ENH] Add Travis CI

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, orangecontrib/network/widgets/OWNxFile.py
Checking if `QFileDialog` returns `filename` sometimes causes an exception somewhere in the code.
Also add issue and pull request templates.
=> [FIX] File: filename check

orangecontrib/network/widgets/OWNxExplorer.py, orangecontrib/network/widgets/graphview.py, orangecontrib/network/widgets/tests/test_OWNxExplorer.py
Connect **Network Generator** and **Network Explorer**. The latter fails because it cannot open context since this graph does not have a `Domain` (nor `Table`).
=> [FIX] Network Explorer: do not fail on a graph without domain

orangecontrib/network/widgets/OWNxGenerator.py
Network Generator used the limit of 500 nodes, which is not enough to test any serious functionality of the network widgets.
Limit was increased to 99999.
=> Increased limit for the size of the network

orangecontrib/network/widgets/OWNxExplorer.py
Widget window size is too wide and this is caused by
```python
self.setSceneRect(-1e5, -1e5, 2e5, 2e5)
```
in file `graphview.py` (see: https://github.com/biolab/orange3-network/blob/4a5d6d2de816d73fc3d14540fbc3538b25caeeaa/orangecontrib/network/widgets/graphview.py#L238).
However this line is needed.
=> [FIX] Network Explorer: widget windows size

orangecontrib/network/widgets/OWNxGenerator.py, orangecontrib/network/widgets/tests/test_OWNxGenerator.py
Current algorithm which creates _balanced tree_ is fast but not very accurate.
For a given number of nodes it creates a tree which has very different number of nodes. In the range from `5` to `10000` the error varies up to `88%` and the average error is about `7.5%`.
The new algorithm has an average error about `0.65%` and maximum `33.5%`.
This algorithm is not yet optimized and is written in a non pythonic way.
=> [ENH] Network Generator: new algorithm balanced tree

orangecontrib/network/widgets/OWNxExplorer.py, orangecontrib/network/widgets/graphview.py
Only arrow is shown and therefore a user does not know that is over a node, etc.
Mouse cursor changes when moving nodes around or when hovering above the node. Something similar like in **Radviz** and **FreeViz** widgets.
Also some code cleaning.
=> [ENH] Network Explorer: change mouse cursor

orangecontrib/network/widgets/OWNxExplorer.py, orangecontrib/network/widgets/tests/test_OWNxExplorer.py
Open **Network Explorer** and click _Show edge weights_.
=> [FIX] Network Explorer: do not fail on no graph and one clicks

orangecontrib/network/widgets/OWNxGenerator.py
**Network Generator** widget got a different signal name but the back compatibility was not set.
Argument `replaces` fixes this problem.
~**Test will be added when #65 is merged.**~
=> [FIX] Generator: output signal replace old signal name

orangecontrib/network/widgets/OWNxGenerator.py, orangecontrib/network/widgets/tests/test_OWNxGenerator.py
Sometimes one selects low number of nodes and higher degree is generated by random generator. That causes widget **Network Generator** to fail.
Number of degree is corrected if higher than or equal number of nodes. Note that test still passes 10% of a time without a fix.
=> [FIX] Network Generator: regular graph: degree less than nodes

orangecontrib/network/readwrite.py
Similar to https://github.com/biolab/orange3/pull/2416
=> [FIX] Readwrite: use unicode

orangecontrib/network/widgets/OWNxExplorer.py, orangecontrib/network/widgets/tests/test_OWNxExplorer.py
See screenshot below. Notice that data from **File** widget are sent as _Node Subset_.
Then select nodes in **Network Explorer**. Widget crashes.
_... from Node Subset input signal_ is not selected in second tab (_Marking_) when there is no proper subset data.
=> [FIX] Network Explorer: do not crash on selecting nodes when no items

orangecontrib/network/widgets/graphview.py
Open hand cursor is shown above an edge as well. It should not.
Open hand cursor is now shown only above node.
=> [FIX] Network Explorer: show open hand cursor only above node

.travis.yml
Fix travis build.
Pin PyQt5 to 5.9.2
=> travis: pin PyQt5==5.9.2 to avoid segfault

orangecontrib/network/_fr_layout.cpp, orangecontrib/network/_fr_layout.pyx, orangecontrib/network/widgets/OWNxExplorer.py, orangecontrib/network/widgets/graphview.py
Added an option for re-layout with or without randomization.
Reduced the temperature schedule for a smoother visualization of networks and re-layout of visualizations that were modified/improved by hand (by dragging some sets of nodes to appropriate places).
=> [ENH] OWNxExplorer: Re-layout randomization

orangecontrib/network/community.py, orangecontrib/network/widgets/OWNxClustering.py, orangecontrib/network/widgets/tests/test_OWNxClustering.py
Crashed when node data domain already contained variable named "Cluster".
Fix. Move cluster annotations from `target_var` to metas.
=> OWNxClustering: Fix crash when Cluster variable existed in data

orangecontrib/network/widgets/OWNxExplorer.py
`onDeleteWidget` called a method with a wrong name, which for some unknown reason remained unnoticed.
=> Network Explorer: Fix wrong method name (stop_optimization_blocking)

orangecontrib/network/widgets/OWNxFile.py, orangecontrib/network/widgets/tests/test_OWNxFile.py
Network widget does not handle exceptions thrown in file readers. In the worst case, this can even prevent the widget from initializing if the file it attempts to read is invalid.
This bug was first tackled in #89, but the problem does not occur only in `__init__` (where #89 fixes it), and it's a result of inappropriate handling of exceptions in the function that calls the reader, so it should be fixed there.
Improved handling of exceptions.
=> OWNxFile: Catch all exceptions in reader

.travis.yml
Orange is now tested with Python 3.6.
=> Test with Python 3.6

orangecontrib/network/widgets/OWNxClustering.py
OWNxClustering widget doesn't load with the latest version of orange because of a discontinued method get_next_name (https://github.com/biolab/orange3/pull/3486).
Replace it by its new substitute get_unique_names.
=> [FIX] OWNxClustering: doesn't load due to discontinued method get_next_name

setup.py
Network add-on doesn't work with current version of Orange because of changes in OWPlotGui ( (GH-3432).
#96 already fixed this, but the new version isn't yet published on PyPi and Conda.
=> Bump version to 1.4.2

orangecontrib/network/widgets/OWNxExplorer.py
When the Network Explorer was disconnected from input, or input is set to None, the widget did not reset.
`self.positions` is now set to `None` before checking whether the network is not `None` and small enough. This signals `handleNewSignals` to reset the graph.
=> OWNxExplorer: Reset widget when input is lost

orangecontrib/network/widgets/OWNxClustering.py, orangecontrib/network/widgets/OWNxFile.py, orangecontrib/network/widgets/tests/test_OWNxExplorer.py
`OWWidget.info` has a new meaning and its use as an attribute is deprecated.
Attribute is renamed to `infolabel`.
=> NxFile, NxExplorer: Rename info to infolabel

orangecontrib/network/network/readwrite.py, orangecontrib/network/widgets/OWNxExplorer.py, orangecontrib/network/widgets/tests/test_OWNxExplorer.py
Fixes #120. 
- Inherit warnings and errors from OWDataProjectionWidget class instead of base widget class.
- Replace single quotes with double for warnings.
- Add tests.
- Fix a small error in reading the file.
=> OWNetworkExplorer: Inherit warnings and errors from DataProjectionWidget class.

orangecontrib/network/network/base.py, orangecontrib/network/widgets/tests/test_OWNxExplorer.py
Fixes #121. 
Fix the call for selecting a subset and add tests.
=> OWNetworkExplorer: fix selecting a subset in the plot

orangecontrib/network/network/base.py, orangecontrib/network/widgets/OWNxFromDistances.py, orangecontrib/network/widgets/tests/test_OWNxFromDistances.py
Network from Distances crashed on Largest Component and Component with at least N nodes.
Correctly compute masks for selection of subsets.
=> OWNxFromDistances: fix selection of nodes

orangecontrib/network/widgets/OWNxFromDistances.py
Buttons in Node selection box not aligned.
Align buttons by placing them in QGridLayout.
=> OWNxFromDistances: Align buttons

orangecontrib/network/network/community.py
Fixes tests that are failing due to the use of deprecated `Table.concatenate` in `community.py`.
Remove the use of `Table.concatenate` and replace it with an alternative way, similar to the one, suggested here: https://github.com/biolab/orange3/issues/3908#issuecomment-506643467
=> [FIX] Fix failing clustering tests

orangecontrib/network/network/readwrite.py
- Network Explorer crashed for graphs read from Pajek's edges lists, supported by the new reader. 
This happened because the reader was smart enough to store edges as unsigned chars, which reduced memory usage by a factor of 8, but FR code in Cython expects doubles.
- Fixes #138. The bug was probably in networkx, which we no longer use, but it is also present in the current master. Pajek format is largely undocumented, hence supporting it requires a lot of guess work.
- This PR changes dtype of edges, returned by the reader, to double.
- It also stores edges of unweighted graphs with a sparse matrix in which `data` is written in a single `double` but with stride set to 0 to fake a constant array of required size without wasting memory.
- For #138, it properly treats indices.
=> Pajek Reader: Fixes in node indices and edge weights

orangecontrib/network/widgets/OWNxFile.py
Fixes #125.
This widget will always show an error, warning or info, so text like "123 nodes and 234 edges" stands no chance to fit in. I changed the summary to "123 / 234" (less too long) and kept the tooltip text.
I also fixed the mixed up numbers (Thanks, @matejklemen! LOL :).
=> Network File: Fix status line

orangecontrib/network/network/base.py, orangecontrib/network/widgets/OWNxExplorer.py, orangecontrib/network/widgets/graphview.py, orangecontrib/network/widgets/tests/test_OWNxExplorer.py
Fixes #128.
Also makes the counter for selected nodes work.
#128 describes two issues:
1. _For some nodes, its component does not get selected._ 
This is due to the fact that edges are represented with sparse matrices. The following line accounts for the bidirectional links, but when summing two sparse matrices, the explicit zeros (i.e. edges with zero weight) get lost.  
`self.twoway_edges = self.edges + self.edges.transpose()`
Therefore, neighbors of a node, that are connected by a single, zero weight edge, are not found anymore. 
The proposed solution is to manually re-add the zero weight edges.
2. _Upon triple clicking on a node, an error pops up._ 
This is due to a method returning a `np.array`, which then produces a `np.array` of booleans, for which the "truthness" is not defined. …
=> Network explorer fixes

orangecontrib/network/network/twomode.py, orangecontrib/network/tests/test_twomode.py
Addresses #129 (I did not implement the second part of that issue, just fixed the crashing).
Multiple minor fixes:
- fixed the crashing;
- fixed an existing test: the masks for `mode_mask` and `conn_mask` were off. To my understanding, a node can either be "projected to", be used as a connection or none of these two ("ignored"), but it **can't** be both projected to and used as a connection;
- added a new test that would cause a crash before this fix.
The problem seemed to be that the adjacency matrix for the new (single-mode) network had the wrong shape - it was of shape `(#edges_in_projected_network, #edges_in_projected_network)`, when it should really be of dimension `(#projected_nodes, #projected_nodes)`.
Here's the visual form of the new test, maybe it will help when checking …
=> [FIX] Fix single-mode widget crashing

orangecontrib/network/widgets/OWNxExplorer.py, orangecontrib/network/widgets/tests/test_OWNxExplorer.py
When an empty network was fed into Network Explorer, it would crash due to zero division error in line
```self.edges_per_node = self.number_of_edges / self.number_of_nodes```.
Besides the example in the test, this can also be reproduced with the following workflow:  
**Network File** (last.fm) -> **Single Mode** (`best_tag`, connect `00s` by `(all others)`) -> **Network Explorer**.
The problem was actually that the check for a network having 0 nodes used `net.number_of_nodes` instead of `net.number_of_nodes()`.
=> Fix Network Explorer crashing on empty network input

.travis.yml, .travis/install_orange.sh, .travis/util.sh
Tests started failing in send_report. Unfixing Qt version didn't help. Copying the test configuration from text add-on does.
=> Improve Travis configuration

orangecontrib/network/network/base.py, orangecontrib/network/widgets/OWNxFile.py, orangecontrib/network/widgets/OWNxFromDistances.py, orangecontrib/network/widgets/tests/test_graphview.py
Gets rid of deprecation warnings and fixes a (locally) failing test due to relative import.
- get rid of deprecation warnings from Orange's `gui` module: change values in `orientation=` argument from `str` to `Qt` objects  
- fix locally failing test in `test_graphview.py`: change relative import to absolute import  
- get rid of numpy's `FutureWarning`: Numpy decided to drop support for generator inputs (see https://github.com/numpy/numpy/pull/12280) to `np.stack` family of functions, so the current generator expression is turned into a list comprehension
=> [FIX] Fix deprecation warnings and locally failing test

orangecontrib/network/network/generate.py, orangecontrib/network/tests/test_twomode.py, orangecontrib/network/widgets/OWNxAnalysis.py, orangecontrib/network/widgets/tests/test_OWNxAnalysis.py, orangecontrib/network/widgets/tests/utils.py
A few minor fixes and QoL additions.
1. Change density and average degree to have different values based on network type (different formulas).
These were previously generally calculated, though they have different formulas based on network type.  
2. Automatically "shadow" network statistics that are not meant to be used with input network's type (e.g. strongly connected components for undirected networks).
Assigned "general" usability (both directed/undirected) by default, a few statistics were restricted to directed networks only.
3. Minor fix in `cancel_job(...)`: properties that don't exist for a `str` were mistakenly being called.
4. Fix crash when requesting report.
Report name was missing - it can be `""` (now), but it can't be unspecified in function call (before).
=> Network analysis fixes/improvements

orangecontrib/network/widgets/ownxsinglemode.py, orangecontrib/network/widgets/tests/test_ownxsinglemode.py
Fixes #110 
Assigns a local "mode" -1 to nodes whose connection variable values are missing, so that it doesn't match any possible value (since categorical values are encoded with integers >= 0). A warning also gets displayed, telling the user that nodes with missing data are being ignored.
Unrelated to #110, I've also swapped some `Table(<domain>)` calls with `Table.from_domain(<domain>)` in tests due to deprecation warnings.
=> Handle missing values in single mode

orangecontrib/network/widgets/OWNxFromDistances.py, orangecontrib/network/widgets/tests/test_OWNxFromDistances.py
Fixes #161 and some other minor problems.
The issue in #161 was due to not being able to infer a sensible distance threshold automatically because a distance matrix for 1 row contains only the self-distance, which is ignored when determining this threshold. The solution is to manually set the threshold to 0 in that case.
The second issue was that typing in 100. percentile would make the widget crash, due to the index corresponding to 100th percentile being out of bounds by 1 (`table[len(table)]`). I have changed the percentiles a bit so that the 0th and 100th percentile get mapped to some valid percentiles, corresponding to min and max.
The third issue (which was mostly possible due to 100th percentile being taken as valid) was that the distance threshold would automatically be set below …
=> OWNxFromDistances: fix crashes on certain inputs

.travis.yml, orangecontrib/network/network/embeddings.py, orangecontrib/network/tests/test_embeddings.py, orangecontrib/network/widgets/OWNxEmbeddings.py, setup.py
Introduces a new widget (Network embeddings) and a method for embedding nodes into vectors, [node2vec](https://arxiv.org/abs/1607.00653).
The method (very briefly described) works in 2 steps:
1. Obtain sequences of random walks across the network. These walks are guided by two parameters, **p** and **q**.
2. Run word2vec on these sequences to obtain embeddings.
The method and widget already work, but some things need to be improved. 
I'd appreciate any comments regarding the widget.
=> [ENH] Node2vec node embeddings

orangecontrib/network/widgets/tests/test_ownxsinglemode.py
`Discrete.values` must be tuples.
=> SingleMode tests: define DiscreteVariable.values as tuple

orangecontrib/network/widgets/graphview.py, orangecontrib/network/widgets/tests/test_OWNxExplorer.py
Implements #145 and fixes edge weight display when using mark criteria in Network Explorer.
If a single node is selected, current behaviour is used. Otherwise, show edge weights only between selected nodes.
Additionally, when using mark criteria (e.g. `Mark nodes with many connections`), it would sometimes not show edge weights - for example, if `Show edge weights` was already checked before.
1. If more than one node is selected, a check is performed to select only those edges where both the source and target are marked.
2. When updating marked nodes, `update_edge_labels()` also gets called now.
=> Network Explorer: if more than one node selected, show weights only for edges between selected nodes

orangecontrib/network/widgets/OWNxExplorer.py, orangecontrib/network/widgets/tests/test_OWNxExplorer.py
Fixes #158.
Fixes #144 (well, not directly, but implements the alternative proposed in #158, that solves this issue).
Subset data was not being registered properly. Calling `_handle_subset_data()` sets `subset_indices` properly and then the scatterplot-like highlighting starts working.
=> OWNxExplorer: automatically highlight input network subset

orangecontrib/network/widgets/OWNxExplorer.py
Fixes #142. I tried
- a grid with 9801 vertices and 19404 edges,
- a 12d hypercube with 4096 vertices and 49152,
and both, FR and drawing, worked reasonably fast. Though you can't see anything, so I'd only push it to 100.000.
=> Network Explorer: Increase the limit for network size

orangecontrib/network/widgets/ownxsinglemode.py
Fixes #151. 
Context handler's `match_values` flag was incorrectly set to `True` (which equaled 1, which equaled `MATCH_VALUES_CLASS`) instead of to `MATCH_VALUES_ALL`).
=> [FIX] Single Mode: Fix crash when variable value was removed

orangecontrib/network/network/base.py, orangecontrib/network/widgets/OWNxExplorer.py, orangecontrib/network/widgets/graphview.py
`numpy.bool` is [deprecated in Numpy 1.20](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations), which results in numerous warnings like
```
DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
`bool` and `np.bool` are equal in the sense that `bool == np.bool` returns `True`.
=> Replace np.bool and with bool

orangecontrib/network/widgets/OWNxGroups.py, orangecontrib/network/widgets/tests/test_OWNxGroups.py
Add tests for group weights (fixes #99).
Minor changes:
- indent checkbox for normalization that is applicable when selecting the last radio button; disables it when inapplicable.
- use the standard `WidgetPreview`.
=> Add tests for Network Groups

.github/workflows/test.yml
Tests fail because widget minimum size too wide on Windows https://github.com/biolab/orange3-network/pull/192
I found out that Qlablel's text which is 165px wide is more than 500px wide on Windows when `QT_QPA_PLATFORM=offscreen`. Also, the font family is different without `QT_QPA_PLATFORM=offscreen` `MS Shell Dlg 2` is used and with `QT_QPA_PLATFORM=offscreen` font-family is `Helvetica`. I tried to google it but cannot find a similar bug with `QT_QPA_PLATFORM=offscreen`. There are just some bugs reported with some fonts not accessible on Windows (which could be the reason for the different font but not the reason for too wide text). The height of the text is similar in both cases. 
Since I do not find the exact reason for the issue and `QT_QPA_PLATFORM=offscreen` is not required on …
=> Disable QT_QPA_PLATFORM=offscreen on Windows GH Action tests

orangecontrib/network/widgets/OWNxAnalysis.py
The new orange-widget-base introduces some UI changes.
Refactors the controls such that all the checkboxes are in their own box, yielding spacing and margins coherent with MacStyle on Mac.
=> Network Analysis: Refactor to two vBoxes

orangecontrib/network/widgets/OWNxFile.py, setup.py
Fixes #187.
Requires https://github.com/biolab/orange3/pull/5238.
The problem described in #187 occurs if the environment is inconsistent. This should only happen on developers' machines and not in properly installed Orange.
Call `Orange.util.get_entry_point`, which skips tests.
=> Network File: Avoid resolving requirements in search for entry point

setup.py
Orange already depends on them and the add-on will never depend on higher versions than Orange. Besides, these versions are never updated, so it's better to remove them.
Fixes #198.
=> Remove numpy and pyqtgraph from requirements

orangecontrib/network/network/embeddings.py, orangecontrib/network/widgets/OWNxExplorer.py, setup.py, tox.ini
Crashes and failed tests due to incompatibility with Orange 3.29 and other dependencies.
- Unpin some dependencies and require Orange 3.29
- Fix a problem with summaries that appears because Network Explorers `Inputs` are not derived from `Inputs` of its parent class, but still calls the input handler for those inputs
- TBD: Fix parameters of `gensim`'s `Word2Vec`.
=> Updates for Orange 3.29

orangecontrib/network/widgets/OWNxFromDistances.py
Fixes #216.
Put zeros on the diagonal of the mask. Prior to that, convert `mask` to array, otherwise it's `DistMatrix` and `numpy.fill_diagonal` doesn't work.
=> Network from distances: Remove loops

orangecontrib/network/network/base.py, orangecontrib/network/widgets/OWNxClustering.py
Fixes #226.
Copy the network before adding labels.
No tests. Tests that a nonsense bug was removed are stupid. We test functionality, not non-functionality.
=> [FIX] Network Clustering: Don't add labels to input network

doc/conf.py, doc/index.rst, doc/static/custom.css, orangecontrib/network/widgets/__init__.py, setup.py
The documentation for the Orange3-networks module was not working before since there were no entries for docs location.
AND
While ago we discussed that we will use the same documentation theme for add-ons. After some discussion, we decided on sphinx-rtd-theme. The alternative is Alabaster but its sidebar is not so readable and it breaks long addon names in two lines.
With this PR I am implementing the sphinx-rtd-theme. I also changed that the menu bar collapses on the medium screen already (before it collapsed on small screens). On the medium screen, the content column was narrow already and it works well for widget documentation in Orange since at the default Orange help window size the sidebar is collapsed.
=> Change documentation theme to sphinx_rtd_theme and enable the documentation

orangecontrib/network/widgets/graphview.py
Fixes #229.
For unweighted networks, the widths are stored in a float rather than numpy array, and can't be indexed.
Distinguish between the two cases.
No tests. This is in `PlotVarWidthCurveItem.paint` and thus rather untestable.
=> Network Explorer: Fix drawing of unweighted networks with arcs

orangecontrib/network/tests/test_twomode.py, orangecontrib/network/widgets/OWNxAnalysis.py
`np.float` is deprecated and should replaced with `float` to avoid warnings (https://numpy.org/doc/stable/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated).
=> [MNT] Replace deprecated numpy type aliases

orangecontrib/network/widgets/OWNxSave.py
As of https://github.com/biolab/orange3/pull/5560, `OWSaveBase.writer` can be `None`.
In this case, do not save. Error will be set in the base class.
This PR does not depend on https://github.com/biolab/orange3/pull/5560 and can be merged anytime.
The potential bug that it fixes currently cannot occur.
=> Save: Don't crash on unsupported format

doc/conf.py, orangecontrib/network/widgets/__init__.py, setup.py
In https://github.com/biolab/orange3-educational/pull/109 we changed the documentation theme to shpinx rtd theme. It was found out that it does not support htmlhelp builder. 
Since with this theme, it is not required to build the documentation with htmlhelp I am changing the setting such that they are compatible with html builder. From now on we build documentation with `make html` instead of `make htmlhelp`
=> Documentation: enable building with html builder

orangecontrib/network/widgets/OWNxFile.py, orangecontrib/network/widgets/__init__.py, orangecontrib/network/widgets/tests/test_ownxsinglemode.py, setup.py, tox.ini
Orange 3.31 locks tables (in tests)
- Unlock table in File widget and in tests for single mode. 
- Require Orange 3.31
- Assume Python > 3.7
=> Unlock tables

.github/workflows/build_wheels.yml
build_wheels will always attempt to publish wheels when triggered with workflow_dispatch.
Skip publishing on manually run. Publish only on release (new tag).
=> Update build_wheels.yml - Publish only on tag

.github/workflows/build_wheels.yml, setup.py
The network doesn't build successfully after Cython 3 release
Fixup build - use cythonize
Additional cleanup: 
- Remove try-except around Cython import since we have pyporoject.toml which makes sure that Cython is always installed.
- Remove the error that raises when no Cython or Numpy is present (same reason)
- Change keywords and classifiers to List since Tuple is not accepted anymore
=> setup.py - Fix cython build and cleanup

.github/workflows/build_wheels.yml, pyproject.toml, setup.py
The network does not build wheels for Python>3.9, and it doesn't provide wheels for MacOS - arm 
Update wheel building to:
- build wheels in parallel
- build all wheels that also Orange3 offers
- move configuration in pyproject.toml
- some other minor updates
=> [CI] Wheels - Update wheels building

setup.py
According to https://github.com/conda-forge/orange3-network-feedstock/pull/22, pyqtgraph is missing in dependencies.
Adding pyqtgraph to dependecies
=> Add pyqtgraph to dependencies

orangecontrib/network/network/layout/_fr_layout.pyx, tox.ini
- With `cdivision=true`, dividing two ints resulted in an `int`,
- and were also stored into `Py_ssize_t`,
- with the former also masking a division by zero,
- in a place where the division was unnecessary anyway.
Luckily, this probably didn't effect the algorithm a lot.
=> FR: Divide into double, not Py_ssize_t

orangecontrib/network/widgets/OWNxFile.py, orangecontrib/network/widgets/tests/test_OWNxFile.py
Fixes #266.
Somebody wrote crappy code that didn't count on two variables being an equally suitable match for the label.
Furthermore, he wrote crappy tests.
Me, that is.
=> Network File: Fix crash when two variables are equally preferable

orangecontrib/network/network/layout/__init__.py, orangecontrib/network/widgets/OWNxExplorer.py, orangecontrib/network/widgets/graphview.py, orangecontrib/network/widgets/tests/test_OWNxExplorer.py
Fixes #238. Fixes #219.  Fixes #190.
- Use `ConcurrentMixin` instead of (incorrect) threads created in the widget code.
- Change the FR to report progress in 0.5 second intervals instead of on certain number of steps. This makes it smoother (the points no longer have essential tremor) and increases responsiveness (at least in cases I tried).
- Fix: convert dtype to `np.int32`, as expected by Cython code. The network can, in principle, have edges in, e.g. `np.int64`. (The bug was discovered when Network of Neighbors had return a net with such dtype.)
- Several lint-related changes (including one actual fix)
=> Network Explorer: Replace (crashing) threads with ConcurrentMixin

orangecontrib/network/network/base.py, orangecontrib/network/widgets/OWNxFromDistances.py, orangecontrib/network/widgets/OWNxNeighbor.py, orangecontrib/network/widgets/__init__.py, orangecontrib/network/widgets/icons/NetworkOfNeighbors.svg, orangecontrib/network/widgets/tests/test_OWNxFromDistances.py, orangecontrib/network/widgets/tests/test_ownxneighbor.py, orangecontrib/network/widgets/tests/test_utils.py, orangecontrib/network/widgets/utils.py, setup.py, tox.ini
Fixes #250. Fixes #248. Fixes #243.
**Reimplementation of Network from Distances**. Widget is cleaner and leaner.
- The new implementation allows setting the number of edges or density (or threshold, as before). All of these can be edited numerically or set in a graph.
- The widget handles asymmetric matrices (should we have any).
- Instead of histogram with number of edges at a particular distances, the graph is now cumulative; this allows for showing the threshold and the number of edges in the same graph.
- Creating network of closest neighbors is removed to a separate widget.
- Extracting the largest components / removal of small components is not longer possible. It may resurrect in a separate widget, dedicated to selection of components.
- Better tests.
**Network of Neighbours:** A …
=> Reimplement Network from Distances

orangecontrib/network/widgets/OWNxExplorer.py, orangecontrib/network/widgets/tests/test_OWNxExplorer.py
Fixes #264.
Add match by exact label.
@ajdapretnar, if this works for you, feel free to merge. There will be no tests; this widget is what it is -- largely untested. Adding a new option at the beginning (changing the indices of all options) bothered only a single test. :(
=> Network Explorer: Add exact match by label

.github/workflows/release.yml
Releasing using reusable workflows currently cannot use PyPI's Trusted Publishing. https://github.com/pypi/warehouse/issues/11096
We are moving back to secret for uploading.
=> Release workflow - Inherit secrets

orangecontrib/network/network/base.py
Methods that return neighbours or ingoing or outgoing connections fail if `weights=True`. This code was obviously never used and never tested.
Network widgets are in dire need of unit tests. :(
A fix would be to add a pair of parentheses (`vstack` expects a tuple, not multiple arguments).
However, node indices are ints and weights are floats, so we should put them into the same array. Instead, the function now returns a tuple. Since nobody could have used the code, we need not care about backward compatibility.
=> Fix neighbors/outgoing/ingoing with weights=False

i18n/si/msgs.jaml, i18n/trubar-config.yaml, orangecontrib/network/__init__.py, orangecontrib/network/network/__init__.py, orangecontrib/network/network/base.py, orangecontrib/network/network/twomode.py, orangecontrib/network/networks/makeNetworkList.py, orangecontrib/network/tests/test_twomode.py, orangecontrib/network/widgets/tests/test_ownxsinglemode.py, setup.py, tox.ini
=> Minor random fixes
